export enum actiontypes {
    FETCH_DEFINITIONS_REQUESTED = "FETCH_DEFINITIONS_REQUESTED",
    // FETCH_DEFINITIONS_SUCCESS = "FETCH_DEFINITIONS_SUCCESS",
    // FETCH_DEFINITIONS_FAILURE = "FETCH_DEFINITIONS_FAILURE",
    SET_WORD = "SET_WORD",
    GET_WORD = "GET_WORD"
}